# Generated by Django 2.2 on 2019-04-27 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0007_auto_20190427_1224'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('time', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('course', models.FloatField(blank=True, null=True)),
                ('ele', models.FloatField(blank=True, null=True)),
                ('hacc', models.FloatField(blank=True, null=True)),
                ('vacc', models.FloatField(blank=True, null=True)),
                ('hdop', models.FloatField(blank=True, null=True)),
                ('vdop', models.FloatField(blank=True, null=True)),
                ('pdop', models.FloatField(blank=True, null=True)),
                ('tdop', models.FloatField(blank=True, null=True)),
                ('sat', models.IntegerField(blank=True, null=True)),
                ('satavail', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datalogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Datalogger')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('datalogger', 'time')},
            },
        ),
    ]
