# Generated by Django 2.2 on 2019-04-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0006_auto_20190423_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trackpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('alt', models.FloatField(blank=True, null=True)),
                ('acc', models.FloatField(blank=True, null=True)),
                ('vac', models.FloatField(blank=True, null=True)),
                ('vel', models.FloatField(blank=True, null=True)),
                ('batt', models.FloatField(blank=True, null=True)),
                ('conn', models.CharField(blank=True, max_length=16)),
                ('tid', models.CharField(blank=True, max_length=16)),
                ('time', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datalogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broker.Datalogger')),
            ],
            options={
                'unique_together': {('datalogger', 'time')},
            },
        ),
    ]
